eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
