server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:movie.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

info:
  app:
    name: movie-service
    description: Movie Service Parcial Backend
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
